Postgres:
    host: 34.173.103.16
    port: 5432
    database: postgres
    query: "SELECT * FROM public.venda;"

Urls:
    api: "https://us-central1-bix-tecnologia-prd.cloudfunctions.net/api_challenge_junior"
    parquet: "https://storage.googleapis.com/challenge_junior/categoria.parquet"

Output:
    host: localhost
    port: 5432
    database: bix_challenge

